const LISTPOKEMON = {
  LOADING: 'LISTPOKEMON_LOADING',
  FETCH_SUCCESS: 'LISTPOKEMON_FETCH_SUCCESS',
  FETCH_FAILED: 'LISTPOKEMON_FETCH_FAILED',
  FETCH_IMAGE_SUCCESS: 'LISTPOKEMN_FETCH_SUCCESS',
  FETCH_IMAGE_FAILED: 'LISTPOKEMN_FETCH_FAILED',
};

const POKEMONDETAIL = {
  LOADING: 'POKEMONDETAIL_LOADING',
  FETCH_DETAIL_SUCCESS: 'POKEMONDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILED: 'POKEMONDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_ADD_POKEMON: 'POKEMONDETAIL_FETCH_ADD_POKEMON',
  RESET_DETAIL: 'POKEMONDETAIL_RESET_DETAIL',
};

export { LISTPOKEMON, POKEMONDETAIL };
